### ISSUE TITLE
Expose a straightforward  API

### ISSUE THREAD

**Issue by pedagand** [AugustinBariant/Projet3A#3]
As far as I understand the code, the meat of algorithm is implemented in `Optimizer.java`. However, it seems that a `search` method, taking an input permutation and producing a sequence of instructions, is missing. Instead, we can find this code in the `main` procedure.

Refactor your code such that the search algorithm is provided as a method. As a result, `main` should just call `search`.

**Comment by pedagand** [comment]
To move on with my review, I've provided a stub `search` method in `Optimizer.java` but I think that it does not belong there. There should be a new class that encapsulates a `List<Optimizer> L` and uses `Optimizer` to implement the search. Feel free to move `search` there.

**Comment by AugustinBariant** [comment]
Done with OptimizerSolver
